# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-11 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='papers.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=521)),
                ('favorite', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bibcite', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('authors', models.CharField(max_length=256)),
                ('organization', models.CharField(max_length=256)),
                ('year', models.DateField()),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=256)),
                ('doi', models.CharField(max_length=256)),
                ('journal', models.CharField(max_length=256)),
                ('volume', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=128)),
                ('pages', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Paper_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cite_number', models.PositiveSmallIntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='papers.Paper')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='papers.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='relation',
            field=models.ManyToManyField(through='papers.Paper_relation', to='papers.Paper'),
        ),
        migrations.AddField(
            model_name='paper',
            name='tag',
            field=models.ManyToManyField(to='papers.Tag'),
        ),
    ]
