# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-21 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20161121_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='path',
        ),
        migrations.AddField(
            model_name='paper',
            name='downloaded',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_file',
            field=models.FileField(default=None, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper_relation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_source', to='papers.Paper'),
        ),
        migrations.AlterField(
            model_name='paper_relation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_target', to='papers.Paper'),
        ),
    ]
