# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-21 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_auto_20161121_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='relation',
            new_name='parent',
        ),
    ]
