# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-21 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_auto_20161121_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='relate_paper',
        ),
        migrations.AddField(
            model_name='paper',
            name='references',
            field=models.ManyToManyField(related_name='citers', through='papers.Paper_relation', to='papers.Paper'),
        ),
    ]
