# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-21 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_auto_20161121_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='references',
            field=models.ManyToManyField(related_name='citers', related_query_name='citer', through='papers.Paper_relation', to='papers.Paper'),
        ),
    ]
