# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-28 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_auto_20161121_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
