# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-30 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0009_auto_20161130_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='authors',
            new_name='author',
        ),
    ]
