# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-03 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0010_auto_20161130_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='bib_type',
            new_name='bibtype',
        ),
        migrations.RemoveField(
            model_name='paper_relation',
            name='source',
        ),
        migrations.RemoveField(
            model_name='paper_relation',
            name='target',
        ),
        migrations.AddField(
            model_name='paper_relation',
            name='citer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='as_citer', to='papers.Paper'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper_relation',
            name='reference',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='as_reference', to='papers.Paper'),
            preserve_default=False,
        ),
    ]
