# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-04 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0011_auto_20161203_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='papers.Category'),
        ),
    ]
