# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-04 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0014_auto_20161204_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='tag',
            field=models.ManyToManyField(to='papers.Tag'),
        ),
    ]
