# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-08 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0015_auto_20161204_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='bib_file',
            field=models.FileField(blank=True, null=True, upload_to='/bib/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_file',
            field=models.FileField(blank=True, null=True, upload_to='/paper/%Y/%m/%d/'),
        ),
    ]
