# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-09 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0017_auto_20161208_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='papers.Tag'),
        ),
    ]
